apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: listingops-com-tls
spec:
  secretName: listingops-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: listingops.com
  dnsNames:
    - listingops.com
    - www.listingops.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - listingops.com
          - www.listingops.com
